version: '3.8'

services:
  db:
    image: postgres:17
    container_name: eduplan_postgres_container
    environment:
      POSTGRES_DB: eduplan_db
      POSTGRES_USER: sarm_m
      POSTGRES_PASSWORD: sebastian123pro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
