-- Compatible with an empty database or the original Hibernate-created schema.
-- Existing tables are kept intact. Hibernate validate checks model compatibility afterwards.
CREATE TABLE IF NOT EXISTS cuenta (
 id_cuenta bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 correo varchar(80) NOT NULL, contrasena varchar(80) NOT NULL,
 estado boolean NOT NULL, fecha_registro timestamp NOT NULL
);
CREATE TABLE IF NOT EXISTS estudiante (
 id_estudiante bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre varchar(100) NOT NULL, apellido varchar(100) NOT NULL,
 grado varchar(100) NOT NULL, departamento varchar(100) NOT NULL,
 municipio varchar(100) NOT NULL, presupuesto numeric(10,2),
 modalidad_preferida varchar(100), id_cuenta bigint UNIQUE REFERENCES cuenta(id_cuenta)
);
CREATE TABLE IF NOT EXISTS institucion (
 id_institucion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre varchar(100) NOT NULL, tipo varchar(100), ciudad varchar(100),
 departamento varchar(100), direccion text, descripcion text, sitio_web varchar(255)
);
CREATE TABLE IF NOT EXISTS programa_academico (
 id_programa bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre varchar(100) NOT NULL, modalidad varchar(100), duracion varchar(100),
 costo numeric(10,2), requisitos varchar(100), descripcion text,
 nivel_formacion varchar(100), id_institucion bigint REFERENCES institucion(id_institucion)
);
CREATE TABLE IF NOT EXISTS test (
 id_test bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 fecha date NOT NULL, id_estudiante bigint REFERENCES estudiante(id_estudiante)
);
CREATE TABLE IF NOT EXISTS pregunta (
 id_pregunta bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 texto text NOT NULL, categoria varchar(255), id_test bigint REFERENCES test(id_test)
);
CREATE TABLE IF NOT EXISTS respuesta (
 id_respuesta bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 respuesta varchar(100) NOT NULL, id_pregunta bigint REFERENCES pregunta(id_pregunta)
);
CREATE TABLE IF NOT EXISTS resultado_test (
 id_resultado bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 porcentaje_match numeric(10,2) NOT NULL, id_test bigint REFERENCES test(id_test),
 id_programa bigint REFERENCES programa_academico(id_programa)
);
CREATE TABLE IF NOT EXISTS entidad_financiera (
 id_entidad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre varchar(100) NOT NULL, tipo varchar(100), sitio_web varchar(255)
);
CREATE TABLE IF NOT EXISTS ayuda_financiera (
 id_ayuda bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre varchar(100) NOT NULL, descripcion text, porcentaje numeric(10,2), requisitos text,
 fecha_inicio timestamp NOT NULL, fecha_limite timestamp NOT NULL, enlace text,
 tipo_financiacion varchar(100), id_entidad bigint REFERENCES entidad_financiera(id_entidad),
 id_institucion bigint REFERENCES institucion(id_institucion)
);
CREATE TABLE IF NOT EXISTS interes (
 id_interes bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 fecha_interes date, id_estudiante bigint REFERENCES estudiante(id_estudiante),
 id_programa bigint REFERENCES programa_academico(id_programa)
);
CREATE TABLE IF NOT EXISTS postulacion (
 id_postulacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 fecha_postulacion date, estado varchar(50),
 id_estudiante bigint REFERENCES estudiante(id_estudiante),
 id_programa bigint REFERENCES programa_academico(id_programa)
);
