-- Personal exploration data is independent of the imported catalog tables.
CREATE TABLE cuenta_guardado (
 id_guardado bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_cuenta bigint NOT NULL REFERENCES cuenta(id_cuenta) ON DELETE CASCADE,
 referencia varchar(200) NOT NULL,
 tipo varchar(30) NOT NULL CHECK (tipo IN ('program', 'institution', 'opportunity')),
 nombre varchar(500) NOT NULL,
 enlace varchar(1000) NOT NULL,
 resumen text,
 fecha_guardado timestamp with time zone NOT NULL,
 fecha_actualizacion timestamp with time zone NOT NULL,
 CONSTRAINT cuenta_guardado_referencia_unique UNIQUE (id_cuenta, referencia),
 CONSTRAINT cuenta_guardado_resumen_object CHECK (resumen IS NULL OR jsonb_typeof(resumen::jsonb) = 'object'),
 CONSTRAINT cuenta_guardado_resumen_size CHECK (resumen IS NULL OR octet_length(resumen) <= 8192)
);
CREATE INDEX cuenta_guardado_fecha_idx ON cuenta_guardado(id_cuenta, fecha_guardado DESC);

CREATE TABLE cuenta_intereses (
 id_cuenta bigint PRIMARY KEY REFERENCES cuenta(id_cuenta) ON DELETE CASCADE,
 areas text NOT NULL,
 motivaciones text NOT NULL,
 fecha_actualizacion timestamp with time zone NOT NULL,
 CONSTRAINT cuenta_intereses_arrays CHECK (jsonb_typeof(areas::jsonb) = 'array' AND jsonb_typeof(motivaciones::jsonb) = 'array')
);
