-- Independent of imported program entities and the data synchronization process.
CREATE TABLE programa_enlace_dominio (
 institucion varchar(30) NOT NULL,
 dominio varchar(253) NOT NULL,
 PRIMARY KEY (institucion, dominio)
);
CREATE TABLE programa_enlace (
 id varchar(64) PRIMARY KEY,
 fuente_id varchar(200) NOT NULL,
 institucion varchar(30) NOT NULL,
 url varchar(2000) NOT NULL,
 estado varchar(20) NOT NULL CHECK (estado IN ('PENDING','VERIFIED','REJECTED','UNAVAILABLE')),
 evidencia text NOT NULL CHECK (octet_length(evidencia) <= 16000),
 manual boolean NOT NULL DEFAULT false,
 motivo varchar(1000) NOT NULL DEFAULT '',
 comprobado timestamp with time zone NOT NULL,
 verificado timestamp with time zone,
 actualizado timestamp with time zone NOT NULL,
 UNIQUE (fuente_id, url)
);
CREATE INDEX programa_enlace_fuente_idx ON programa_enlace(fuente_id, estado);
CREATE TABLE programa_enlace_historial (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 enlace_id varchar(64) NOT NULL REFERENCES programa_enlace(id),
 accion varchar(30) NOT NULL,
 estado varchar(20) NOT NULL,
 evidencia text NOT NULL,
 motivo varchar(1000) NOT NULL,
 fecha timestamp with time zone NOT NULL
);
