import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const {chromium}=createRequire(import.meta.url)(process.env.EDUPLAN_PLAYWRIGHT_PATH || 'playwright');
const browser=await chromium.launch({channel:process.env.EDUPLAN_BROWSER_CHANNEL || 'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const base=process.env.EDUPLAN_TEST_URL || 'http://localhost:3005';
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const template={sourceId:'upr9-nkiz:a',code:'11',name:'Ingeniería de Sistemas',nameOrigin:'SNIES_NAME',reviewRequired:false,rawName:'Bogotá D.C.',awardedTitle:'Ingeniero de Sistemas',institutionName:'Universidad Alfa',institutionCode:'1701',municipality:'Bogotá D.C.',department:'Bogotá D.C.',academicLevel:'Pregrado',educationLevel:'Universitaria',knowledgeArea:'Ingeniería de sistemas',modality:'Presencial',periodCount:'8',periodicity:'Semestral',credits:'144',status:'Activo',institutionWebsite:'https://alfa.edu.co',institutionSector:'Oficial',institutionCampus:'Principal'};
const programs=[template,{...template,sourceId:'upr9-nkiz:b',code:'12',institutionName:'Universidad Beta',institutionCode:'1702',municipality:'Medellín',department:'Antioquia',modality:'Virtual',periodCount:'10',credits:'160',institutionWebsite:'https://beta.edu.co',institutionSector:'Privada'},{...template,sourceId:'upr9-nkiz:c',code:'13',institutionName:'Universidad Gamma',institutionCode:'1703',municipality:'Cali',department:'Valle del Cauca',credits:'',institutionWebsite:'',institutionCampus:''}];
const selection=programs.map(program=>({id:program.sourceId,sourceId:program.sourceId,code:program.code,name:program.name,nameOrigin:'SNIES_NAME',provenance:'real',institution:program.institutionName,city:program.municipality,level:'Pregrado',duration:'Resumen antiguo',modality:program.modality,status:'Activo'}));
await page.addInitScript(selection=>{if(!sessionStorage.getItem('comparison-fixture-seeded')){localStorage.setItem('eduplan-compare-v1-guest',JSON.stringify(selection));sessionStorage.setItem('comparison-fixture-seeded','true');}},selection);
let mode='ready';const calls=[];
await page.route(/\/api\/programs\/\d+(?:\?|$)/,route=>{
  const code=new URL(route.request().url()).pathname.split('/').at(-1);calls.push(code);
  if(mode==='offline' && code==='12')return route.fulfill({status:502,json:{error:true}});
  const data=mode==='missing' && code==='12' ? [{...programs[1],sourceId:'upr9-nkiz:another-campus',institutionName:'No debe reemplazar la selección'}] : programs.filter(program=>program.code===code);
  return route.fulfill({json:{data}});
});
await page.route('**/api/program-links/batch?**',route=>route.fulfill({json:{data:programs.filter(program=>new URL(route.request().url()).searchParams.getAll('sourceId').includes(program.sourceId)).map(program=>({sourceId:program.sourceId,status:program.code==='11'?'VERIFIED':'NOT_FOUND',...(program.code==='11'?{url:'https://alfa.edu.co/ingenieria',checkedAt:'2026-10-01T00:00:00Z'}:{})}))}}));
const out=fileURLToPath(new URL('../../.tools/qa/comparison/',import.meta.url));await mkdir(out,{recursive:true});
try{
  await page.goto(base+'/comparar');
  await page.getByText('Datos actualizados para esta comparación. Confirma la oferta vigente con cada institución.',{exact:false}).waitFor();
  assert.equal(await page.locator('.comparison-option').count(),3);
  assert.equal(new Set(calls).size,3);
  assert.equal(await page.getByText('Resumen antiguo',{exact:true}).count(),0);
  const duration=page.locator('#compare-study .compare-desktop tr').filter({hasText:'Duración publicada'});
  assert.deepEqual(await duration.locator('td').allTextContents(),['8 semestres','10 semestres','8 semestres']);
  assert.equal(await page.locator('#compare-study .compare-desktop tr').filter({hasText:'Créditos académicos'}).getByText('Por confirmar',{exact:true}).count(),1);
  assert.equal(await page.getByRole('link',{name:'Visitar página oficial del programa ↗',exact:true}).getAttribute('href'),'https://alfa.edu.co/ingenieria');
  assert.equal(await page.getByRole('link',{name:'Sitio de la institución ↗',exact:true}).count(),2);
  assert.equal(await page.getByRole('heading',{name:'Costos, admisión y plan de estudios',exact:true}).count(),1);
  const differenceToggle=page.getByLabel('Ocultar coincidencias',{exact:true});
  await differenceToggle.check();
  await page.locator('#compare-formation .comparison-all-same').waitFor();
  assert.equal(await page.locator('#compare-study .compare-desktop tr').filter({hasText:'Estado publicado'}).count(),0);
  assert.equal(await page.locator('#compare-study .compare-desktop tr').filter({hasText:'Créditos académicos'}).count(),1);
  await differenceToggle.uncheck();
  assert.equal(await page.getByText('El título y el nivel de formación ayudan a distinguir programas con nombres parecidos.',{exact:true}).count(),0);
  await page.getByRole('button',{name:'Título y formación',exact:true}).click();
  await differenceToggle.check();
  await page.locator('#compare-formation .compare-desktop .comparison-row-priority').first().waitFor();
  assert.equal(await page.locator('#compare-formation .compare-desktop tr').filter({hasText:'Título que otorga'}).count(),1);
  await differenceToggle.uncheck();
  const favorite=page.locator('.comparison-option').first().getByRole('button',{name:/^Marcar como favorita:/});
  await favorite.click();
  assert.equal(await favorite.getAttribute('aria-pressed'),'true');
  await page.locator('.comparison-option').nth(1).getByRole('button',{name:/^Marcar como favorita:/}).click();
  assert.equal(await favorite.getAttribute('aria-pressed'),'false');
  assert.equal(await page.locator('.comparison-option-favorite').count(),1);
  await favorite.click();
  assert.equal(await page.locator('.comparison-summary').getByRole('heading',{name:'Las diferencias principales',exact:true}).count(),1);
  assert.equal(await page.locator('.comparison-highlight-grid article').count(),4);
  await page.getByRole('button',{name:'Duración',exact:true}).click();
  assert((await page.locator('.comparison-highlight-grid article').first().textContent()).includes('Duración publicada'));
  await page.getByRole('button',{name:'Duración',exact:true}).click();
  await page.getByText('Compartir comparación',{exact:true}).click();
  const shared=page.getByLabel('Vista previa del resumen',{exact:true});
  assert((await shared.inputValue()).includes('registro=upr9-nkiz%3Aa'));
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Descargar resumen',exact:true}).click();
  assert.equal((await downloadPromise).suggestedFilename(),'comparacion-eduplan.txt');
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedComparison=text;}}}));
  await page.getByRole('button',{name:'Copiar resumen',exact:true}).click();
  await page.getByText('Comparación copiada. Puedes pegarla en el chat o correo que prefieras.',{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.copiedComparison),await shared.inputValue());
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('blocked');}}}));
  await page.getByRole('button',{name:'Copiar resumen',exact:true}).click();
  await page.getByText('No pudimos copiar automáticamente. Selecciona el texto de abajo o descarga el resumen.',{exact:true}).waitFor();
  const note=page.getByLabel('Notas personales para Universidad Alfa',{exact:true});
  await note.fill('Matrícula: consultar con admisiones. Preguntar por horarios.');
  await page.reload();
  await page.getByText('Datos actualizados para esta comparación. Confirma la oferta vigente con cada institución.',{exact:false}).waitFor();
  assert.equal(await note.inputValue(),'Matrícula: consultar con admisiones. Preguntar por horarios.');
  assert.equal(await favorite.getAttribute('aria-pressed'),'true');
  assert.equal(await page.getByRole('button',{name:'Título y formación',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'Título y formación',exact:true}).click();
  await page.locator('.comparison-note-grid article').first().getByRole('button',{name:'Borrar esta nota',exact:true}).click();
  assert.equal(await note.inputValue(),'');
  await note.fill('Mi nota de invitado');
  // Account workspaces are separate; notes are not sent to the account APIs.
  await page.route('**/api/me/**',route=>route.fulfill({status:503,json:{error:true}}));
  await page.evaluate(selection=>{
    sessionStorage.setItem('eduplan-session-v1',JSON.stringify({token:'fixture-token',user:{id:99,name:'Cuenta de prueba',email:'fixture@example.test'},expiresAt:Date.now()+3600000}));
    localStorage.setItem('eduplan-compare-v1-user-99',JSON.stringify(selection));
  },selection);
  await page.reload();await page.locator('.comparison-note-grid textarea').first().waitFor();
  assert.equal(await note.inputValue(),'');
  assert.equal(await favorite.getAttribute('aria-pressed'),'false');
  await note.fill('Nota de la cuenta 99');
  await page.evaluate(()=>sessionStorage.removeItem('eduplan-session-v1'));
  await page.reload();await page.locator('.comparison-note-grid textarea').first().waitFor();
  assert.equal(await note.inputValue(),'Mi nota de invitado');
  assert.equal(await favorite.getAttribute('aria-pressed'),'true');
  await page.getByText('Compartir comparación',{exact:true}).click();
  assert(!(await shared.inputValue()).includes('Mi nota de invitado'));
  await page.getByText('Compartir comparación',{exact:true}).click();
  await page.getByText('Datos actualizados para esta comparación. Confirma la oferta vigente con cada institución.',{exact:false}).waitFor();
  for(const width of [1440,1024,768,390]){
    await page.setViewportSize({width,height:1000});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow at '+width);
    assert.equal(await page.locator('.compare-mobile').first().isVisible(),width<=768);
    await page.screenshot({path:out+'/'+width+'.png',fullPage:true});
    await page.screenshot({path:out+'/'+width+'-viewport.png'});
    await page.locator('.comparison-summary').screenshot({path:out+'/'+width+'-summary.png'});
  }
  mode='offline';await page.getByRole('button',{name:'Actualizar información',exact:true}).click();
  await page.getByText('Mostramos la información que guardaste. Intenta actualizarla de nuevo.',{exact:true}).waitFor();
  assert.equal(await page.locator('.comparison-option').count(),3);
  mode='missing';await page.getByRole('button',{name:'Actualizar información',exact:true}).click();
  await page.getByText('No encontramos esta oferta al actualizar. Confirma con la institución si sigue disponible.',{exact:true}).waitFor();
  assert.equal(await page.getByText('No debe reemplazar la selección',{exact:true}).count(),0);
  mode='ready';await page.getByRole('button',{name:'Actualizar información',exact:true}).click();
  await page.getByText('Datos actualizados para esta comparación. Confirma la oferta vigente con cada institución.',{exact:false}).waitFor();
  await page.locator('.comparison-option').last().getByRole('button',{name:/^Quitar /}).click();
  await page.getByText('2 de 3 programas',{exact:true}).waitFor();
  assert.equal(await page.getByRole('link',{name:'Añadir otra opción',exact:true}).count(),1);
  await page.locator('.comparison-option').last().getByRole('button',{name:/^Quitar /}).click();
  await page.getByText('Ya tienes una opción.',{exact:true}).waitFor();
  assert.equal(await differenceToggle.isDisabled(),true);
  await favorite.click();
  assert.equal(await favorite.getAttribute('aria-pressed'),'false');
  await favorite.click();
  await page.getByRole('button',{name:'Limpiar comparación',exact:true}).click();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('eduplan-comparison-workspace-v1-guest')).favorite),null);
  await page.getByRole('heading',{name:'Aún no has elegido programas',exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({status:'PASS',checked:['current catalog data','published duration and credits','differences and unknowns','official links','cost and admission guidance','refresh failure','missing identity','remove and empty selection','priorities with hidden coincidences','notes persistence and deletion','account separation','favorite persistence and replacement','prioritized highlights','download and clipboard fallback','shared notes privacy'],widths:[1440,1024,768,390]}));
}finally{await browser.close();}
