import { useState } from 'react';
import { Link } from 'react-router-dom';
import DemoNotice from '../components/DemoNotice';
import './pages.css';
const tabs=['Perfil','Mis intereses','Resultados','Configuración'];
const areas=['Tecnología','Salud','Ciencias','Artes','Negocios','Ciencias sociales','Educación'];
const motivations=['Resolver problemas','Ayudar a otros','Crear cosas nuevas','Liderar equipos','Investigar','Trabajar con personas'];
function readSaved(){try{return JSON.parse(localStorage.getItem('eduplan-profile-interests'))||{areas:[],motivations:[]}}catch{return {areas:[],motivations:[]}}}
export default function ProfilePage(){const [tab,setTab]=useState('Mis intereses');const [selections,setSelections]=useState(readSaved);const [saved,setSaved]=useState(false);function toggle(group,value){setSelections(current=>({...current,[group]:current[group].includes(value)?current[group].filter(v=>v!==value):[...current[group],value]}));setSaved(false)}function save(){localStorage.setItem('eduplan-profile-interests',JSON.stringify(selections));setSaved(true)}return <main className="page"><div className="container profile-layout"><aside className="profile-sidebar" aria-label="Accesos de perfil">{[['Inicio','/dashboard'],['Explorar','/programas'],['Instituciones','/instituciones'],['Programas','/programas'],['Becas','/becas'],['Guías','/guias'],['Mi perfil','/perfil'],['Comparar','/comparar']].map(([label,path])=><Link to={path} aria-current={path==='/perfil'?'page':undefined} key={`${label}-${path}`}>{label}</Link>)}</aside><div className="profile-content"><div className="page-intro"><h1>Mi perfil</h1><p className="lead">Organiza tus intereses para explorar programas, instituciones y becas con más claridad.</p></div><DemoNotice/><div className="tabs" role="tablist" aria-label="Secciones del perfil">{tabs.map(item=><button className="tab" role="tab" aria-selected={tab===item} onClick={()=>setTab(item)} type="button" key={item}>{item}</button>)}</div>{tab==='Mis intereses'?<><section className="profile-panel surface"><h2>Mis intereses</h2><p>Selecciona las áreas que te llaman la atención.</p><div className="choice-grid">{areas.map(value=><button className="choice" aria-pressed={selections.areas.includes(value)} type="button" key={value} onClick={()=>toggle('areas',value)}>{selections.areas.includes(value)?'✓ ':''}{value}</button>)}</div></section><section className="profile-panel surface"><h2>¿Qué te motiva?</h2><p>Elige lo que más influye en tu decisión.</p><div className="choice-grid">{motivations.map(value=><button className="choice" aria-pressed={selections.motivations.includes(value)} type="button" key={value} onClick={()=>toggle('motivations',value)}>{selections.motivations.includes(value)?'✓ ':''}{value}</button>)}</div><button className="btn btn-primary profile-save" type="button" onClick={save}>Guardar cambios</button>{saved&&<p role="status" style={{marginTop:12}}>Cambios guardados en este dispositivo.</p>}</section></>:<section className="profile-panel surface"><h2>{tab}</h2><p>{tab==='Perfil'?'Tus datos de cuenta aparecerán aquí cuando se conecte la autenticación.':tab==='Resultados'?'Aquí aparecerán los resultados de orientación cuando estén disponibles.':'Las opciones de cuenta estarán disponibles cuando se conecte la autenticación.'}</p>{tab==='Perfil'&&<Link className="btn btn-secondary" to="/login">Iniciar sesión</Link>}</section>}</div></div></main>}
